---
title: "Literate programming with R Markdown"
description: |
  Literate programming is a technique for meshing source code with a human-readable explanation of its
  logic. This approach is used widely in data science and the social sciences to enable
  reproducible research and open access. In this workshop, we introduce the R Markdown document format
  and practice developing notebooks interweaving source code, output, and written text.
author:
  - name: Benjamin Soltoff
    url: https://www.bensoltoff.com
    affiliation: University of Chicago
    affiliation_url: https://macss.uchicago.edu
date: 11-16-2021
output:
  distill::distill_article:
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Overview

Literate programming is a technique for meshing source code with a human-readable explanation of its logic. This approach is used widely in data science and the social sciences to enable reproducible research and open access. In this workshop, we introduce [`rmarkdown`](https://rmarkdown.rstudio.com/) and the R Markdown document format, and practice developing notebooks interweaving source code, output, and written text.

## Objectives

- Review the importance of reproducibility in scientific research
- Identify the major components of R Markdown documents
- Practice writing Markdown formatted text
- Define `knitr` chunks
- Implement chunk options to customize output
- Create different R Markdown document formats
- Distinguish R Markdown documents from R Markdown notebooks
- Distinguish between R scripts (`.R`) and R Markdown documents (`.Rmd`)

## Audience

This workshop is designed for individuals with a basic familiarity using R for data analysis.

## Location

Room 295 in [1155 E 60th St](https://goo.gl/maps/7n7wDsd9mjnfRBtR8).

## Prework

- Register for this workshop. Due to the current public health crisis, all participants must register in advance using [this form.](https://forms.gle/emnkcwCRb2jsUadf8)
- Please sign up for a free [RStudio Cloud account](https://rstudio.cloud).
- If you have not participated in a previous workshop meeting, [join the workshop organization.](https://rstudio.cloud/spaces/177434/join?access_code=cGV7c0V8%2Bpr0kFC5NkOX%2FgxNNhIm3PchWX1CjdBf)


## Links

- [Slides](https://css-skills.github.io/rmarkdown/slides/)
- [Source materials for the workshop on GitHub](https://github.com/css-skills/rmarkdown)


